#!/bin/bash
# mkdir ${HOME}/.kube
# remove ${HOME/.kube/conf
# save your kubeconf files named *.kubeconf

CONFDIR="${HOME}/.kube"
CONFARRAY=()
SETFILE="${HOME}/.kubeconf"

## listing kubeconfig file up
for i in `ls ${CONFDIR}/*.kubeconfig`
do
  CONFARRAY+=(${i})
done

## show and select menu
idx=0
for i in ${CONFARRAY[@]}
do
  echo "[" ${idx} "]" ${i}
  idx=$((idx + 1))
done
echo
echo -n "Enter number of config you want: "
read ENT

## filter wrong input
if [[ ${ENT} > ${#CONFARRAY[@]} ]]
then
  echo "Wrong select"
  exit 2
fi

## set env
echo "Set" ${CONFARRAY[${ENT}]}

## change logic to make config from env
#echo "export KUBECONFIG=${CONFARRAY[${ENT}]}" > ${SETFILE}
#source ${SETFILE}
#$MYSHELL

ln -sf ${CONFARRAY[${ENT}]} ${CONFDIR}/config

